"""Independent original scalar eager-BF16 fixture; stdlib only, no native/model imports.
Generate: python3 native/tests/full_golden.py > /tmp/full_golden.hpp
Uses frozen prefix matrices and double-precision dot/softmax equations, with
explicit BF16 tensor boundaries, instead of native in-place state loops.
"""
import math
import struct

def f(x):
    return struct.unpack('<f',struct.pack('<f',x))[0]

def bits(x):
    v=struct.unpack('<I',struct.pack('<f',x))[0]
    return (v+0x7fff+((v>>16)&1))>>16

def bf(x):
    return struct.unpack('<f',struct.pack('<I',bits(x)<<16))[0]

def norm(x,w):
    # FP32 normalization, followed by a single BF16 conversion after (1+w).
    total=0
    for v in x:total=f(total+f(v*v))
    inv=f(1/f(math.sqrt(f(f(total/len(x))+f(1e-6)))))
    return [bf(f(f(v*inv)*f(1+weight))) for v,weight in zip(x,w)]

def rotate(x,position):
    result=x.copy()
    for j,frequency in enumerate(frequencies):
        angle=f(position*frequency);cs=bf(math.cos(angle));sn=bf(math.sin(angle))
        result[j]=bf(bf(x[j]*cs)-bf(x[j+2]*sn))
        result[j+2]=bf(bf(x[j]*sn)+bf(x[j+2]*cs))
    return result

def encode(x):
    for byte in range(256):
        sign=-1 if byte&128 else 1;exponent,mantissa=(byte>>3)&15,byte&7
        if exponent==15 and mantissa==7:continue
        decoded=sign*(mantissa*2**-9 if exponent==0 else (1+mantissa/8)*2**(exponent-7))
        if decoded==x:return byte
    raise ValueError(x)

inputs=[[1,2,-1],[-2,1,.5],[.5,-1,2],[1,.5,-2]]
qg=[]
for h in range(4):
    qg += [[.25*(1+(h+j)%3),(-1)**j*.125*(h+1),(-1)**h*.125*(j+1)] for j in range(6)]
    qg += [[(-1)**h*.125*(j+1),.25*(-1)**j,.125*(h+1)] for j in range(6)]
key=[[(-1)**j*.25*(h+1),.125*(j+1),.25*(-1)**h] for h in range(2) for j in range(6)]
value=[[.125*(j+1),(-1)**(h+j)*.25,.25*(h+1)] for h in range(2) for j in range(6)]
out=[[(-1)**(r+h+j)*.125*(1+(r+h+2*j)%3) for h in range(4) for j in range(6)] for r in range(3)]
input_norm=[.125,-.25,.5];query_norm=[.25,-.125,.5,0,-.25,.125];key_norm=[-.25,.25,.125,-.125,.5,0]
frequencies=[1,f(.1)] # theta=100, rotary_dim=4

def project(matrix,x):return [bf(sum(a*b for a,b in zip(row,x))) for row in matrix]

keys=[];values=[];results=[]
for position,token in enumerate(inputs):
    x=norm(token,input_norm);qgate=project(qg,x);kp=project(key,x);vp=project(value,x)
    queries=[rotate(norm(qgate[h*12:h*12+6],query_norm),position) for h in range(4)]
    gates=[qgate[h*12+6:h*12+12] for h in range(4)]
    keys.append([rotate(norm(kp[h*6:h*6+6],key_norm),position) for h in range(2)])
    values.append([vp[h*6:h*6+6] for h in range(2)])
    core=[];gated=[];prob=[]
    for h in range(4):
        # Immutable prefix key/value matrices; row @ transpose(K), then softmax @ V.
        kh=h//2
        logits=[bf(bf(sum(a*b for a,b in zip(queries[h],entry[kh])))*f(1/math.sqrt(6))) for entry in keys]
        exps=[math.exp(score-max(logits)) for score in logits]
        probabilities=[bf(e/sum(exps)) for e in exps]
        prob += probabilities+[0]*(4-len(probabilities))
        row=[bf(sum(probabilities[t]*values[t][kh][j] for t in range(position+1))) for j in range(6)]
        core+=row
        gated += [bf(v*bf(1/(1+math.exp(-g)))) for v,g in zip(row,gates[h])]
    residual=[bf(a+b) for a,b in zip(token,project(out,gated))]
    keybits=[bits(v) for entry in keys for head in entry for v in head]+[0]*(12*(3-position))
    valbits=[bits(v) for entry in values for head in entry for v in head]+[0]*(12*(3-position))
    results.append((keybits,valbits,prob,core,gated,residual))

print('// Generated by full_golden.py; independent prefix-matrix equations.\n#pragma once\n#include <array>\n#include <cstdint>\nnamespace full_golden {')
def emit(name,values,typ='float'):
    def number(x):return float(x).hex()+'f' if typ=='float' else str(x)
    if isinstance(values[0],list):
        print(f'inline constexpr std::array<std::array<{typ},{len(values[0])}>,{len(values)}> {name}{{{{')
        for row in values:print('    {{'+','.join(number(x) for x in row)+'}},')
        print('}};')
    else:print(f'inline constexpr std::array<{typ},{len(values)}> {name}{{'+','.join(number(x) for x in values)+'};')
for name,matrix in [('qg',qg),('key',key),('value',value),('out',out)]:emit(name,[encode(x) for row in matrix for x in row],'std::uint8_t')
for name,values in [('input_norm',input_norm),('query_norm',query_norm),('key_norm',key_norm),('frequencies',frequencies)]:emit(name,values)
emit('inputs',inputs)
for j,name in enumerate(['keys','values','probabilities','core','gated','residual']):emit(name,[r[j] for r in results],'std::uint16_t' if j<2 else 'float')
print('} // namespace full_golden')
