"""Independent scalar-equation fixture, Python stdlib only; no native/model imports.
Regenerate: python3 native/tests/linear_golden.py > native/tests/linear_golden.hpp
Recurrence uses the expanded matrix identity, with a frozen old state, rather
than the production decay/predict/delta in-place loops. Float64 recurrence
arithmetic intentionally differs; bounded FP32 error is checked by the tests.
Other dtype boundaries: IEEE float32 operations and BF16 ties-to-even.
"""
import math
import struct

def f(x):
    return struct.unpack('<f', struct.pack('<f', x))[0]

def bits(x):
    u = struct.unpack('<I', struct.pack('<f', x))[0]
    return (u + 0x7fff + ((u >> 16) & 1)) >> 16

def bf(x):
    return struct.unpack('<f', struct.pack('<I', bits(x) << 16))[0]

def sigmoid(x):
    e = f(math.exp(-abs(x)))
    return f(1 / f(1 + e)) if x >= 0 else f(e / f(1 + e))

def dot(a, b):
    return bf(sum(x*y for x, y in zip(a, b)))

def norm(x, w, offset=False):
    total = 0
    for v in x:
        total = f(total + f(v*v))
    # C++ CPU mean expression promotes size_t division to float.
    inv = f(1 / f(math.sqrt(f(f(total / len(x)) + f(1e-6)))))
    return [bf(f(f(v*inv)*f(1+z))) if offset else bf(f(bf(f(v*inv))*z)) for v,z in zip(x,w)]

inputs = [[1,2,-1],[-2,1,.5],[.5,-1,2],[1,.5,-2]]
q = [[1,.5,-.25],[-.5,1,.25],[.25,-.5,1],[1,.25,.5]]
k = [[.75,.25,1],[-.25,1,.5],[1,-.25,.75],[.5,1,-.25]]
v = [[.25*(h+1),.125*(j+1),(-1)**(h+j)*.125*(h+j+1)] for h in range(4) for j in range(3)]
z = [[(-1)**j*.125*(h+1),.25*(j+1),(-1)**h*.25] for h in range(4) for j in range(3)]
out = [[(-1)**(r+h+j)*.125*(1+(r+2*h+j)%4) for h in range(4) for j in range(3)] for r in range(3)]
input_norm = [.125,-.25,.5]
conv = [[-.25,.5,.75] if ch%3==1 else [.25,-.5,1] for ch in range(20)]
a = [[.25,-.125,.5],[-.5,.25,.125],[.125,.5,-.25],[.5,-.25,-.125]]
b = [[-.25,.5,.125],[.125,-.5,.25],[.5,.125,-.25],[-.125,.25,.5]]
logs = [-.5,0,.25,.5]
dt = [.25,-.125,.5,-.25]
gate = [.75,1.25,.5]

def encode(x):
    # Fixture coefficients are exactly E4M3FN representable (scale = 1).
    for byte in range(256):
        sign = -1 if byte & 128 else 1
        exp, mant = (byte >> 3) & 15, byte & 7
        if exp == 15 and mant == 7:
            continue
        value = sign * (mant*2**-9 if exp == 0 else (1+mant/8)*2**(exp-7))
        if value == x:
            return byte
    raise ValueError(x)

history = [[0.0]*3 for _ in range(20)]
state = [[[0.0]*3 for _ in range(2)] for _ in range(4)]
results = []
for token in inputs:
    x = norm(token,input_norm,True)
    projected = [dot(row,x) for row in q+k+v]
    zed = [dot(row,x) for row in z]
    av, bv = [dot(row,x) for row in a], [dot(row,x) for row in b]
    activated = []
    for ch in range(20):
        history[ch] = history[ch][1:]+[projected[ch]]
        raw = dot(history[ch],conv[ch])
        activated.append(bf(f(raw*sigmoid(raw))))
    queries,keys = [],[]
    for h in range(2):
        for dest,base,is_q in [(queries,2*h,True),(keys,4+2*h,False)]:
            pair = activated[base:base+2]
            denom = f(math.sqrt(f(f(f(pair[0]*pair[0])+f(pair[1]*pair[1]))+f(1e-6))))
            inv = f(1/denom)
            dest.append([f(f(t*inv)/f(math.sqrt(2))) if is_q else f(t*inv) for t in pair])
    core=[]
    for h in range(4):
        t=f(av[h]+dt[h]); soft=f(max(t,0)+f(math.log1p(f(math.exp(-abs(t))))))
        decay=f(math.exp(f(-f(math.exp(logs[h]))*soft)))
        beta=bf(sigmoid(bv[h])); key=keys[h//2]; query=queries[h//2]
        values=activated[8+3*h:11+3*h]
        old=state[h]
        # Independent matrix identity: decay*(I-beta*k*k^T)@old + beta*k*v^T.
        transform=[[decay*((1 if i==j else 0)-beta*key[i]*key[j]) for j in range(2)] for i in range(2)]
        state[h]=[[sum(transform[i][j]*old[j][c] for j in range(2))+beta*key[i]*values[c] for c in range(3)] for i in range(2)]
        core += [bf(sum(query[i]*state[h][i][c] for i in range(2))) for c in range(3)]
    gated=[]
    for h in range(4):
        normalized=norm(core[3*h:3*h+3],gate)
        gated += [bf(f(normalized[j]*f(zed[3*h+j]*sigmoid(zed[3*h+j])))) for j in range(3)]
    residual=[bf(f(token[r]+dot(out[r],gated))) for r in range(3)]
    results.append(([f(x) for head in state for row in head for x in row], [bits(x) for row in history for x in row], residual, core, gated))

print('// Generated by linear_golden.py; independent matrix-identity recurrence.\n#pragma once\n#include <array>\n#include <cstdint>\nnamespace linear_golden {')
def emit(name, vals, typ='float'):
    def number(v):
        if typ=='float':
            return float(v).hex()+'f'
        return str(v)
    if isinstance(vals[0],list):
        print(f'inline constexpr std::array<std::array<{typ},{len(vals[0])}>,{len(vals)}> {name}{{{{')
        for row in vals: print('    {{'+','.join(number(x) for x in row)+'}},')
        print('}};')
    else:
        print(f'inline constexpr std::array<{typ},{len(vals)}> {name}{{'+','.join(number(x) for x in vals)+'};')
for name,matrix in [('qkv',q+k+v),('z',z),('out',out)]:emit(name,[encode(x) for row in matrix for x in row],'std::uint8_t')
for name,vals in [('norm',input_norm),('conv',[x for row in conv for x in row]),('a',[x for row in a for x in row]),('b',[x for row in b for x in row]),('logs',logs),('dt',dt),('gate',gate)]:emit(name,vals)
emit('inputs',inputs)
for j,name in enumerate(['state','history','residual','core','gated']):emit(name,[r[j] for r in results], 'std::uint16_t' if j==1 else 'float')
print('} // namespace linear_golden')
