"""Independent stdlib MoE equations; no native/model/GPU imports.
Generate: python3 native/tests/moe_golden.py > /tmp/moe_golden.hpp
Fixture FP4 codes, scales and globals are defined arithmetically, then decoded
into small explicit matrices. Dense dot/softmax use double accumulation with
explicit BF16 tensor boundaries. No production code supplies expected values.
"""
import math
import struct

def f(x):return struct.unpack('<f',struct.pack('<f',x))[0]
def bf(x):
    u=struct.unpack('<I',struct.pack('<f',x))[0]
    return struct.unpack('<f',struct.pack('<I',(u+0x7fff+((u>>16)&1))&0xffff0000))[0]
def code(e,role,r,j):return (r+2*j+3*e+role)%5+(8 if (r+j+e+role)%3==0 else 0)
def weight(e,role,r,j):
    nibble=code(e,role,r,j);v=[0,.5,1,1.5,2,3,4,6][nibble&7]*(-1 if nibble&8 else 1)
    scale=.25 if (r+j//16+e+role)%2 else .125
    return f(v*scale*((3*e+role)%4+2)/4)
def matrix(e,role):
    middle=32 if e==4 else 16;rows,columns=(16,middle) if role==2 else (middle,16)
    return [[weight(e,role,r,j) for j in range(columns)] for r in range(rows)]
def project(w,x):return [bf(sum(a*b for a,b in zip(row,x))) for row in w]
def expert(e,x):
    gate=project(matrix(e,0),x);up=project(matrix(e,1),x)
    activation=[bf(bf(g/(1+math.exp(-g)))*u) for g,u in zip(gate,up)]
    return project(matrix(e,2),activation)
inputs=[]
for t,prefix in enumerate([[2,1,-1,-2],[-1,2,1,-2],[-2,-1,2,1],[1,-2,-1,2],[0,0,0,0]]):
    inputs.append(prefix+[0 if t==4 and j==4 else (-1)**(j+t)*.25*(1+(j+t)%3) for j in range(4,16)])
router=[[1 if j==e else .125*(e-1) if j==4 else 0 for j in range(16)] for e in range(4)]
shared_gate=[(-1)**j*.03125*(1+j%3) for j in range(16)]
results=[]
for x in inputs:
    logits=project(router,x);exps=[math.exp(v-max(logits)) for v in logits];prob=[v/sum(exps) for v in exps]
    selected=sorted(range(4),key=lambda e:(-prob[e],e))[:2]
    weights=[bf(prob[e]/sum(prob[j] for j in selected)) for e in selected]
    contributions={e:[bf(v*weights[selected.index(e)]) for v in expert(e,x)] for e in selected}
    routed=[0]*16
    for e in sorted(selected):routed=[bf(a+b) for a,b in zip(routed,contributions[e])]
    factor=bf(1/(1+math.exp(-project([shared_gate],x)[0])))
    shared=[bf(v*factor) for v in expert(4,x)];output=[bf(a+b) for a,b in zip(routed,shared)]
    results.append((selected,logits,[f(v) for v in prob],weights,routed,shared,output))
print('// Generated by moe_golden.py; independent explicit-matrix equations.\n#pragma once\n#include <array>\nnamespace moe_golden {')
def emit(name,rows,typ='float'):
    print(f'inline constexpr std::array<std::array<{typ},{len(rows[0])}>,{len(rows)}> {name}{{{{')
    for row in rows:print('    {{'+','.join(float(x).hex()+'f' if typ=='float' else str(x) for x in row)+'}},')
    print('}};')
emit('inputs',inputs)
for j,name in enumerate(['selected','logits','probabilities','top_weights','routed','shared','result']):emit(name,[r[j] for r in results],'unsigned' if j==0 else 'float')
print('} // namespace moe_golden')
